project:
  type: default
  output-dir: ../docs/slides

format:
  revealjs:
    theme: default
    include-in-header: section-breadcrumb.html
    slide-number: c/t
    progress: true
    menu: true
    overview: true
    code-overflow: wrap
    embed-resources: true
    width: 1280
    height: 720
    pdf-separate-fragments: false
    pdf-max-pages-per-slide: 2
    transition: none
    smaller: false
    scrollable: true
